### ISSUE TITLE
Flatpak version of kdenlive doesn't play nice in menus with repo version

### ISSUE THREAD

**Issue by cefn** [flathub/org.kde.kdenlive#11]
The repository version of Kdenlive creates a file org.kde.kdenlive.desktop in my .local/share/applications/

However, this location is shared with Kdenlive from the Ubuntu repositories. The by-product of this is the Ubuntu version never appears in menus if installed after the flatpak, since apt sees a pre-existing file and doesn't overwrite it. For some users this would mean installing the flatpak version makes it impossible to run the repository version afterward. Of course, you can always run it from the console or Alt+F2 with just `kdenlive`

I noted by contrast that Flowblade has two listings - one for the Flatpak version (named by its flatpak id) and another coming from the .deb version. They both appear in menu listings, and I was able to right-click to edit them with different names for my convenience.

```
~ $ ls -1 ~/.local/share/applications/ | grep -i flow
flowblade.desktop
io.github.jliljebl.Flowblade.desktop
```

**Comment by nedrichards** [comment]
It's important to separate the naming of the desktop file from the source - lots of apps are moving to naming their assets after their app-id rather than a random hodepodge of names that have accreted over time. It's just that this is required in flatpak to be exported. But as @TingPing said, flatpak doesn't write files to that location, so I'm not entirely sure what's happening on your system.

**Comment by eszlari** [comment]
Since this is not a kdenlive specific issue, I'm closing this.
