### ISSUE TITLE
Can't access files in /tmp

### ISSUE THREAD

**Issue by frdbr** [flathub/org.kde.kdenlive#126]
Kdenlive can't access files in /tmp folder. This doesn't happen in AppImage nor in self compiled versions.

**Comment by aleixpol** [comment]
This is a security measure.

Why is it needed?

**Comment by frdbr** [comment]
I for one download sometimes files to /tmp, edit a quick test to debug a report for example or a throwaway project and render if needed. This helps not having to manually delete files afterwards... at least it is a thing I do...

**Comment by jlskuz** [comment]
See here for more information: https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

@frdbr In general I don't think it would be good to allow access to `/tmp` from within the (stable) flatpak. Your workflow is more a development workflow and very specific because you are doing a lot of debugging and software testing. If still needed a solution could be to enable the access on the nightly flatpak… Do you think we can close this issue?

**Comment by frdbr** [comment]
I guess it is not common a usecase.
