### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by David-Else** [flathub/org.kde.kdenlive#160]
Today Flathub says `21.08.3` it is `21.12.0`

**Comment by jlskuz** [comment]
Hi David, thanks for your report! Flathub fetches the version number from the appstream data and due to a KDE release mistake KDE Gear software unfortunately has the wrong version number in the appstream data. With the next version this will be fixed until then it might be good to keep this issue open.

Cheers,
Julius

See also https://mail.kde.org/pipermail/release-team/2021-December/012577.html

**Comment by jlskuz** [comment]
Fixed now, thanks again
