### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by davidlee9023** [flathub/org.kde.kdenlive#22]
massage: flatpak install flathub org.kde.kdenlive
error: app/org.kde.kdenlive/x86_64/stable needs a later flatpak version (0.11.4)

**Comment by nedrichards** [comment]
Which version of flatpak do you have? run `flatpak --version` on the CLI. I assume it's older the 0.11.4 and this flatpak needs features that are only found in that version or newer. If you find that you have a newer version of flatpak than 0.11.4 then feel free to re-open/comment, otherwise you'll need to get a more recent version of flatpak.

If it's flatpak 0.8.8 on RHEL/CentOS then you should look at enabling https://copr.fedorainfracloud.org/coprs/amigadave/flatpak-epel7/ (that's what we use as part of the flathub infrastructure).

**Comment by davidlee9023** [comment]
I am using Debian stretch ,I cannot upgrade flatpak version.my flatpak is Flatpak 0.8.9.

**Comment by nedrichards** [comment]
As noted on the other bug you can get new flatpak from stretch-backports https://packages.debian.org/stretch-backports/flatpak
